FROM ruby:3.4-slim AS base
WORKDIR /app
ENV RAILS_ENV=production
ENV BUNDLE_WITHOUT=development:test
ENV BUNDLE_PATH=/usr/local/bundle

RUN apt-get update -qq && \
  apt-get install --no-install-recommends -y \
  build-essential \
  libpq-dev \
  curl \
  git \
  && rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./
RUN bundle install --jobs 4 --retry 3

COPY . .

CMD ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
