default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: fartlek_development

test:
  <<: *default
  database: fartlek_test

production:
  <<: *default
  database: fartlek_production
  url: <%= ENV["DATABASE_URL"] %>
